---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: google-spark-daintree-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: daintree-dev
    server: 'https://kubernetes.default.svc'
  project: daintree
  source:
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    path: gitops/google-spark-operator/chart/google-spark-operator
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |            
            image:
              repository: image-registry.openshift-image-registry.svc:5000/rainforest-ci-cd/spark-google-operator
              tag: "3.3.0"
            historyimage:
              repository: image-registry.openshift-image-registry.svc:5000/rainforest-ci-cd/spark-history
              tag: "3.3.0"
            imageProxy:
              repository: quay.io/oauth2-proxy/oauth2-proxy
              tag: "v7.3.0"
            resources:
              limits:
                cpu: 500m
            avp:
              secretPath: "kv/data/student/rainforest-ci-cd/daintree-dev/google-spark-operator"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
