---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-access-management-daintree-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: rainforest-ci-cd
    server: 'https://kubernetes.default.svc'
  project: daintree
  source:
    path: gitops/iam/chart/iam
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    targetRevision: main
    helm:
      valueFiles:
        - cluster-dev/daintree-dev/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
