---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radanalytics-spark-daintree-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: daintree-dev
    server: 'https://kubernetes.default.svc'
  project: daintree
  source:
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    path: gitops/radanalyticsio-spark/chart/radanalyticsio-spark
    targetRevision: main
    helm:
      values: |
        sparkRuntimeImage: image-registry.openshift-image-registry.svc:5000/rainforest-ci-cd/spark-rad:3.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
