---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino-daintree-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: daintree-dev
    server: 'https://kubernetes.default.svc'
  project: daintree
  source:
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    path: gitops/trino/chart/trino
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: image-registry.openshift-image-registry.svc:5000/rainforest-ci-cd/ubi-trino
              tag: "413"
            imageWorker:
              repository: image-registry.openshift-image-registry.svc:5000/rainforest-ci-cd/ubi-trino
              tag: "413"
            imageDb:
              repository: registry.redhat.io/rhel8/postgresql-13
              tag: "1-56"
            imageHive:
              repository: image-registry.openshift-image-registry.svc:5000/rainforest-ci-cd/ubi-hive 
              tag: "3.1.3"
            avp:
              secretPath: "kv/data/student/rainforest-ci-cd/daintree-dev/trino"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
