---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-daintree-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: daintree-dev
    server: 'https://kubernetes.default.svc'
  project: rainforest
  source:
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    path: gitops/secrets/cluster-dev/daintree-dev
    targetRevision: main
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
