{{- if .Values.catalogs }}
{{- range $cat := .Values.catalogs }}
{{- if $cat.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cat.name }}-hive-s3-secret
  labels:
    {{- include "hive-metastore.labels" $ | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ $.Values.avp.secretPath }}"
stringData:
  AWS_ACCESS_KEY_ID: <{{ $cat.name | upper }}_HIVE_S3_AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <{{ $cat.name | upper }}_HIVE_S3_AWS_ACCESS_KEY>
  BUCKET: <{{ $cat.name | upper }}_HIVE_S3_BUCKET>
  S3_ENDPOINT: <{{ $cat.name | upper }}_HIVE_S3_ENDPOINT>
  S3_ENDPOINT_URL_PREFIX: <{{ $cat.name | upper }}_HIVE_S3_ENDPOINT_URL_PREFIX>
  S3_DATA_DIR: <{{ $cat.name | upper }}_HIVE_S3_DATA_DIR>
{{- end }}
{{- end }}
{{- end }}
