{{- if .Values.catalogs }}
{{- range $cat := .Values.catalogs }}
{{- if $cat.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cat.name }}-hive-db
  labels:
    {{- include "hive-metastore.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $cat.name }}
  annotations:
    avp.kubernetes.io/path: "{{ $.Values.avp.secretPath }}"
stringData:
  database-password: <{{ $cat.name | upper }}_HIVE_DB_PASSWORD>
  database-host: {{ $cat.name }}-hive-db
  database-port: "5432"
  database-name: <{{ $cat.name | upper }}_HIVE_DB_NAME>
  database-user: <{{ $cat.name | upper }}_HIVE_DB_USERNAME>
{{- end }}
{{- end }}
{{- end }}
