---
apiVersion: v1
kind: Service
metadata:
  name: trino-service
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  ports:
    - name: trino-endpoint
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: metrics
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    {{- include "trino.selectorLabels" . | nindent 4 }}
