---
kind: Service
apiVersion: v1
metadata:
  name: trino-db
  labels:
    {{- include "trinodb.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    {{- include "trinodb.selectorLabels" . | nindent 4 }}