---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trinoworker.fullname" . }}
  labels:
    {{- include "trinoworker.labels" . | nindent 4 }}
  annotations:    
    configmap.reloader.stakater.com/reload: "trino-config,trino-scripts"
    secret.reloader.stakater.com/reload: "trino-config,trino-catalog,trino-truststore,trino-keystore"
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "trinoworker.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "trinoworker.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: trino-config-volume
          secret:
            secretName: trino-config
            defaultMode: 420
            items:
              - key: config-worker.properties
                path: config-worker.properties
              - key: jvm-worker.config
                path: jvm-worker.config
              - key: log.properties
                path: log.properties
              - key: node.properties
                path: node.properties
        - name: trino-catalogs-volume
          secret:
            secretName: trino-catalog
            defaultMode: 420
            items:
              - key: hive.properties
                path: hive.properties
        - name: trino-scripts
          configMap:
            name: trino-scripts
            items:
            - key: entrypoint.sh
              path: entrypoint.sh
              mode: 509
        - name: truststore-volume
          secret:
            secretName: trino-truststore
            defaultMode: 420
            items:
              - key: truststore.jks
                path: truststore.jks
      containers:
        - resources:
            {{- toYaml .Values.resourcesWorker | nindent 12 }}
          name: trino-worker
          command:
            - /etc/trino/scripts/entrypoint.sh
            - /usr/lib/trino/run-trino
            - --etc-dir=/etc/trino
            - --config=/etc/trino/config.properties.worker
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: hive-s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hive-s3-secret
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: trino-config-volume
              mountPath: /etc/trino
            - name: trino-catalogs-volume
              mountPath: /etc/trino/catalog
            - name: trino-scripts
              mountPath: /etc/trino/scripts
            - name: truststore-volume
              mountPath: /etc/trino/truststore
          image: {{ .Values.imageWorker.repository }}:{{ .Values.imageWorker.tag }}
          imagePullPolicy: {{ .Values.imageWorker.pullPolicy }}
          args:
            - --config=/etc/trino/config-worker.properties
            - --jvm-config=/etc/trino/jvm-worker.config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ include "trinoworker.serviceAccountName" . }}
      serviceAccountName: {{ include "trinoworker.serviceAccountName" . }}
      terminationGracePeriodSeconds: 5
