---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config-groups
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
stringData:
  groups.properties: |-
    <GROUPS>
