---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config-rules
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
stringData:
  rules.json: |-
    <RULES>
