replicaCount: 1
replicaCountDb: 1
image:
  repository: quay.io/eformat/mlflow
  pullPolicy: Always
  tag: "2.1.1"
imageProxy:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  pullPolicy: Always
  tag: "v7.3.0"
imageDb:
  repository: registry.redhat.io/rhel8/postgresql-13
  pullPolicy: Always
  tag: "1-56"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nameOverrideDb: ""
fullnameOverrideDb: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
  nameDb: ""
podAnnotations: {}
resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi
resourcesProxy:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
resourcesDb:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi
avp:
  secretPath: ""
s3:
  endpoint_url: ""
  aws_access_key_id: ""
  aws_secret_access_key: ""
  aws_bucket_name: ""
  ignore_tls: "true"
postgresql:
  admin_password: ""
  user: ""
  password: ""
  database: ""
  accessModes:
    - ReadWriteOnce
  storage: 2Gi
proxy:
  provider: ""
  client_id: ""
  client_secret: ""
  cookie_secret: ""
  oidc_issuer_url: ""
  allowed_role: ""
route:
  host: ""
