---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-scoped-rainforest-ci-cd
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: rainforest-ci-cd
    server: 'https://kubernetes.default.svc'
  project: rainforest
  source:
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    path: gitops/cluster-scoped/cluster-dev
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - ServerSideApply=true
