apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radanalytics-spark-rainforest-ci-cd
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: rainforest-ci-cd
    server: 'https://kubernetes.default.svc'
  project: rainforest
  source:
    repoURL: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    path: gitops/radanalyticsio-spark/chart/radanalyticsio-spark-cluster
    targetRevision: main
    helm:
      values: |
        teams:
          daintree:
            namespace: "daintree-dev"
            group: "student"
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
