---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fybrik-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: fybrik-system
    server: 'https://kubernetes.default.svc'
  project: fybrik
  source:
    repoURL: https://fybrik.github.io/charts
    chart: fybrik
    targetRevision: 1.3.1
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            clusterScoped: true
            modulesNamespace:
              name: fybrik-system
              managedByFybrik: false
            applicationNamespace: fybrik-system
            coordinator:
              catalog: openmetadata
            openmetadataConnector:
              openmetadata_endpoint: <path:kv/data/student/rainforest-ci-cd/daintree-dev/fybrik#OPENMETADATA_ENDPOINT>
              openmetadata_user: <path:kv/data/student/rainforest-ci-cd/daintree-dev/fybrik#OPENMETADATA_USER>
              openmetadata_password: <path:kv/data/student/rainforest-ci-cd/daintree-dev/fybrik#OPENMETADATA_PASSWORD>
            vault:
              enabled: true
              address: <path:kv/data/student/rainforest-ci-cd/daintree-dev/fybrik#VAULT_ADDRESS>
            login:
              token: <path:kv/data/student/rainforest-ci-cd/daintree-dev/fybrik#VAULT_TOKEN>
            opaServer:
              podSecurityContext:
                runAsNonRoot: true
                runAsUser: 1000810000   
                seccompProfile:
                  type: RuntimeDefault            
            opaConnector:
              podSecurityContext:
                runAsNonRoot: true
                runAsUser: 1000810000   
                seccompProfile:
                  type: RuntimeDefault
            openmetadataConnector:
              podSecurityContext:
                runAsNonRoot: true
                runAsUser: 1000810000   
                seccompProfile:
                  type: RuntimeDefault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fybrik-crd-dev
  namespace: rainforest-ci-cd
spec:
  destination:
    namespace: fybrik-system
    server: 'https://kubernetes.default.svc'
  project: fybrik
  source:
    repoURL: https://fybrik.github.io/charts
    chart: fybrik-crd
    targetRevision: 1.3.1
    plugin:
      name: argocd-vault-plugin-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
