replicaCount: 1
replicaCountHive: 1
image:
  repository: quay.io/eformat/ubi-trino
  pullPolicy: Always
  tag: "413"
imageWorker:
  repository: quay.io/eformat/trino
  pullPolicy: Always
  tag: "413"
imageDb:
  repository: registry.redhat.io/rhel8/postgresql-13
  pullPolicy: Always
  tag: "1-56"
imageHive:
  repository: quay.io/cloudservices/ubi-hive
  pullPolicy: Always
  tag: "2.3.3-002"
imagePullSecrets: []
nameOverride: ""
nameOverrideDb: ""
nameOverrideHive: ""
nameOverrideWorker: ""
fullnameOverride: ""
fullnameOverrideDb: ""
fullnameOverrideHive: ""
fullnameOverrideWorker: ""
serviceAccount:
  create: false
  annotations: {}
  name: ""
serviceAccountDb:
  create: false
  annotations: {}
  name: ""
serviceAccountHive:
  create: false
  annotations: {}
  name: ""
serviceAccountWorker:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 2Gi
resourcesDb:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 300m
    memory: 300Mi
resourcesHive:
  limits:
    cpu: 750m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 1Gi
resourcesWorker:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 1Gi
database:
  accessModes:
    - ReadWriteOnce
  storage: 2Gi
shared_secret: ""
avp:
  secretPath: ""
catalogs:
  # Hive Demo Catalog
  - name: demo
    enabled: true
