---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    resources:
      limits:
        cpu: 600m
      requests:
        cpu: 300m