---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: RELATED_IMAGE_POSTGRESQL
        value: registry.redhat.io/rhel8/postgresql-13:1-56
      - name: HTTP_PROXY
        value: ""
      - name: HTTPS_PROXY
        value: ""
      - name: NO_PROXY
        value: ""
      - name: KEYCLOAK_LOGLEVEL
        value: DEBUG
