apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-lab-elyra"
    opendatahub.io/notebook-image-name: "Elyra Notebook Image with Spark"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with Elyra-AI installed"
  name: s2i-lab-elyra-spark
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.13"},{"name":"Spark","version":"v3.3.0"},{"name":"elyra","version":"3.9.1"}]'
      openshift.io/imported-from: quay.io/thoth-station/s2i-lab-elyra
    from:
      kind: DockerImage
      name: quay.io/eformat/spark-elyra:3.3.0-elyra-3.9.1
    name: "3.3.0-elyra-3.9.1"
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source

