apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- elyra-notebook-imagestream.yaml
- elyra-notebook-spark3-imagestream.yaml
- elyra-tflow-notebook-imagestream.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
