apiVersion: v1
stringData:
  AIRFLOW_DB: airflow_db
  AIRFLOW_DB_PASSWORD: <AIRFLOW_DB_PASSWORD>
  AIRFLOW_DB_USER: airflow
  OPENMETADATA_DB: openmetadata_db
  OPENMETADATA_DB_PASSWORD: <OPENMETADATA_DB_PASSWORD>
  OPENMETADATA_DB_USER: openmetadata_user
kind: Secret
metadata:
  name: mysql-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/student/rainforest-ci-cd/daintree-dev/openmetadata"
type: Opaque
