{{- $name := include "google-spark-operator-cluster.name" . -}}
{{- $labels := include "google-spark-operator-cluster.labels" . }}
{{- $opFullName := include "google-spark-operator.fullname" . -}}
{{- range $key, $value := .Values.teams }}
{{- if eq ($value.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-{{ $key }}
  namespace: {{ $value.namespace | quote }}
  labels:
    {{- $labels | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $opFullName | quote }}
    namespace: {{ $value.namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ $opFullName | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
