apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spark-history.fullname" . }}
  labels:
    {{- include "spark-history.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["deployments", "pods"]
    verbs: ["*"]
