---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgresql
  labels:
    {{- include "airflowpostgresql.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
type: Opaque
stringData:
  postgresql-admin-password: <POSTGRESQL_ADMIN_PASSWORD>
  postgresql-password: <POSTGRESQL_PASSWORD>
  postgresql-user: <POSTGRESQL_USER>
  postgresql-database: <POSTGRESQL_DATABASE>
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-redis
  labels:
    {{- include "airflowredis.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
type: Opaque
stringData:
  redis-password: <REDIS_PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow
  labels:
    {{- include "airflowscheduler.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
type: Opaque
stringData:
  airflow-password: <AIRFLOW_PASSWORD>
  airflow-fernetKey: <AIRFLOW_FERNETKEY>
  webserver-secret-key: <WEBSERVER_SECRET_KEY>
  oauth-api-base-url: <OAUTH_API_BASE_URL>
  oauth-token-url: <OAUTH_TOKEN_URL>
  oauth-authorize-url: <OAUTH_AUTHORIZE_URL>
  oauth-logout-redirect-url: <OAUTH_LOGOUT_REDIRECT_URL>
  oauth-client-id: <OAUTH_CLIENT_ID>
  oauth-client-secret: <OAUTH_CLIENT_SECRET>
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-proxy
  annotations:
    kubernetes.io/service-account.name:
      {{ include "airflowproxy.serviceAccountName" . }}
type: kubernetes.io/service-account-token
