---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "google-spark-operator.fullname" . }}
  labels:
    app: spark
spec:
  ports:
    - name: metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: spark
