---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "google-spark-operator.fullname" . }}
  labels:
    {{- include "google-spark-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "google-spark-operator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "google-spark-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: sparkoperator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -logtostderr
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "google-spark-operator.serviceAccountName" . }}
