---
apiVersion: v1
stringData:
  username: <GIT_USER>
  password: <GIT_PASSWORD>
  url: <GIT_REPO>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "kv/data/student/rainforest-ci-cd/daintree-dev/git-auth"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: git-auth
