---
apiVersion: v1
kind: Secret
metadata:
  name: superset
  labels:
    {{- include "superset.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
stringData:
  SUPERSET_ADMIN_USER: <SUPERSET_ADMIN_USER>
  SUPERSET_ADMIN_FNAME: <SUPERSET_ADMIN_FNAME>
  SUPERSET_ADMIN_LNAME: <SUPERSET_ADMIN_LNAME>
  SUPERSET_ADMIN_EMAIL: <SUPERSET_ADMIN_EMAIL>
  SUPERSET_ADMIN_PASSWORD: <SUPERSET_ADMIN_PASSWORD>
  SUPERSET_SECRET_KEY: <SUPERSET_SECRET_KEY>
