---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    {{- include "superset.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: 8088-tcp
      port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    {{- include "superset.selectorLabels" . | nindent 4 }}
