---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "supersetdb.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
    avp.kubernetes.io/path: "{{ .Values.avp.secretPath }}"
  name: supersetdb
stringData:
  database-name: <DATABASE_NAME>
  database-password: <DATABASE_PASSWORD>
  database-user: <DATABASE_USER>
