apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "superset.serviceAccountName" . }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"superset"}}'
