apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: superset-rbac-viewer
  labels:
    {{- include "superset.labels" . | nindent 4 }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: superset-rbac-viewer
subjects:
- kind: ServiceAccount
  name: {{ include "superset.serviceAccountName" . }}
