---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: git-sync
  name: git-sync
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: git-sync
  name: git-sync
spec:
  completionDeadlineSeconds: 3600
  resources:
    limits:
      cpu: "300m"
      memory: "2Gi"
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: git-sync:v3.6.6
  postCommit: {}
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/opendatahub-io-contrib/data-mesh-pattern
    type: Git
    contextDir: supply-chain/git-sync/git-sync
    sourceSecret:
      name: git-auth
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.rh
      buildArgs:
      - name: "BUILDER_IMAGE"
        value: "registry.access.redhat.com/ubi8/go-toolset:1.17.12-3"
      - name: "BASE_IMAGE"
        value: "registry.access.redhat.com/ubi8/ubi:8.7-1112"
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 7uqdp8XlkT-IteMISzpt
    type: GitHub
  - generic:
      secret: gR5-Dtb1Ie_6ILQrEcWd
    type: Generic
  - type: ConfigChange
