---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: daintree-dev
  labels:
    realm: daintree-dev
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realm:
    id: "daintree-dev"
    realm: "daintree-dev"
    enabled: true
    displayName: "Rainforest Team daintree-dev Single Sign On Realm"
    loginWithEmailAllowed: false
    registrationAllowed: false
    registrationEmailAsUsername: false
    rememberMe: true
    sslRequired: "external"
    verifyEmail: false
    identityProviders:
      - addReadTokenRoleOnCreate: false
        alias: openshift4
        providerId: openshift-v4
        enabled: true
        firstBrokerLoginFlowAlias: first broker login
        linkOnly: false
        storeToken: false
        trustEmail: true
        config:
          baseUrl: "https://api.foo.sandbox1234.opentlc.com:6443"
          clientId: keycloak-broker-daintree-dev
          syncMode: IMPORT
          clientSecret: <path:kv/data/student/rainforest-ci-cd/daintree-dev/keycloak#BROKER_CLIENTSECRET>
          defaultScope: "user:full"
          useJwksUrl: "true"
    clientScopes:
      - id: minio-authorization
        name: minio-authorization
        description: OpenID Connect scope for minio policy
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
        protocolMappers:
          - id: minio-policy-mapper
            name: minio-policy-mapper
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              aggregate.attrs: "true"
              userinfo.token.claim: "true"
              multivalued: "true"
              user.attribute: "policy"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: "policy"
              jsonType.label: "String"
      - id: 2e00768f-fe3c-48d8-92bf-35afbbcc30c0
        name: web-origins
        description: OpenID Connect scope for add allowed web origins to the access token
        protocol: openid-connect
        attributes:
          include.in.token.scope: "false"
          display.on.consent.screen: "false"
          consent.screen.text: ""
        protocolMappers:
          - id: d54340bc-16f0-45a4-9464-436ef7583a81
            name: allowed web origins
            protocol: openid-connect
            protocolMapper: oidc-allowed-origins-mapper
            consentRequired: false
            config: {}
      - id: 172816fd-8450-4e82-b33a-89f9181373a4
        name: phone
        description: 'OpenID Connect built-in scope: phone'
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
          consent.screen.text: ${phoneScopeConsentText}
        protocolMappers:
          - id: 02c09b15-1210-4a6c-b6e4-c2452031712a
            name: phone number
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: phoneNumber
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: phone_number
              jsonType.label: String
          - id: 6a96110b-3a23-48cd-8d90-cefa6228e5e1
            name: phone number verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: phoneNumberVerified
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: phone_number_verified
              jsonType.label: boolean
      - id: c7d788d8-5836-4500-b4a9-083c2f6c2960
        name: role_list
        description: SAML role list
        protocol: saml
        attributes:
          consent.screen.text: ${samlRoleListScopeConsentText}
          display.on.consent.screen: "true"
        protocolMappers:
          - id: a70dad06-f7a0-4c3d-8c08-cf440c7918da
            name: role list
            protocol: saml
            protocolMapper: saml-role-list-mapper
            consentRequired: false
            config:
              single: "false"
              attribute.nameformat: Basic
              attribute.name: Role
      - id: 656d7d46-bcd6-4b5a-bcfa-20ad0f13e9fe
        name: offline_access
        description: 'OpenID Connect built-in scope: offline_access'
        protocol: openid-connect
        attributes:
          consent.screen.text: ${offlineAccessScopeConsentText}
          display.on.consent.screen: "true"
      - id: 65c7d0bd-243d-42d2-b7f2-64ce2fa7ca7e
        name: profile
        description: 'OpenID Connect built-in scope: profile'
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
          consent.screen.text: ${profileScopeConsentText}
        protocolMappers:
          - id: e3f5a475-0722-4293-bcd5-2bad6bc7dde6
            name: locale
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: locale
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: locale
              jsonType.label: String
          - id: 7b91d2ec-3c9f-4e7d-859e-67900de0c6b6
            name: full name
            protocol: openid-connect
            protocolMapper: oidc-full-name-mapper
            consentRequired: false
            config:
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
          - id: d301c7b7-0d97-4d37-8527-a5c63d461a3c
            name: family name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: lastName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: family_name
              jsonType.label: String
          - id: 71c6caff-3f17-47db-8dc1-42f9af01832e
            name: updated at
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: updatedAt
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: updated_at
              jsonType.label: long
          - id: 6bcb9f8d-94be-48b3-bd47-2ba7746d65ac
            name: picture
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: picture
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: picture
              jsonType.label: String
          - id: d497ef2e-5d5b-4d8a-9392-04e09f5c51b6
            name: nickname
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: nickname
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: nickname
              jsonType.label: String
          - id: f8167604-073d-47ea-9fd1-6ec754ce5c49
            name: website
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: website
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: website
              jsonType.label: String
          - id: 48d8f2ff-d0e6-41f2-839e-3e51951ee078
            name: profile
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: profile
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: profile
              jsonType.label: String
          - id: 463f80df-1554-4f0b-889f-1e6f2308ba17
            name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: username
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: preferred_username
              jsonType.label: String
          - id: c347cd4f-a2e1-4a5f-a676-e779beb7bccf
            name: given name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: firstName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: given_name
              jsonType.label: String
          - id: 665672fd-872e-4a58-b586-b6f6fddbc1ac
            name: zoneinfo
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: zoneinfo
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: zoneinfo
              jsonType.label: String
          - id: b76e46cc-98a9-4bf7-8918-0cc8eb2dfc8c
            name: gender
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: gender
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: gender
              jsonType.label: String
          - id: cb1a55e3-87f0-4efb-b5c0-d5de40344bfc
            name: birthdate
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: birthdate
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: birthdate
              jsonType.label: String
          - id: 9b5c1c92-c937-4216-9fdb-db23d6eee788
            name: middle name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: middleName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: middle_name
              jsonType.label: String
      - id: 672455b2-1e92-44f6-9fb6-fe2017995aed
        name: profile_level.name_and_dev_terms
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
      - id: 45e1900d-2199-45fc-9028-a39497a6cdd5
        name: email
        description: 'OpenID Connect built-in scope: email'
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
          consent.screen.text: ${emailScopeConsentText}
        protocolMappers:
          - id: 149315f5-4595-4794-b11f-f4b68b1c9f7a
            name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: email
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email
              jsonType.label: String
          - id: 26f0791c-93cf-4241-9c92-5528e67b9817
            name: email verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: emailVerified
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email_verified
              jsonType.label: boolean
      - id: ed5b578d-d48f-4023-bc23-892a76d018df
        name: roles
        description: OpenID Connect scope for add user roles to the access token
        protocol: openid-connect
        attributes:
          include.in.token.scope: "false"
          display.on.consent.screen: "true"
          consent.screen.text: ${rolesScopeConsentText}
        protocolMappers:
          - id: 569264db-b779-49c9-a9b0-cfa0f8c249db
            name: audience resolve
            protocol: openid-connect
            protocolMapper: oidc-audience-resolve-mapper
            consentRequired: false
            config: {}
          - id: 6d2e188f-4022-474e-84ad-19a84e054fc5
            name: realm roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            consentRequired: false
            config:
              user.attribute: foo
              access.token.claim: "true"
              claim.name: realm_access.roles
              jsonType.label: String
              multivalued: "true"
          - id: f7b77092-577d-4492-b803-a3cdf2a436fe
            name: client roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-client-role-mapper
            consentRequired: false
            config:
              user.attribute: foo
              access.token.claim: "true"
              claim.name: resource_access.${client_id}.roles
              jsonType.label: String
              multivalued: "true"
      - id: b2240814-1831-48d1-9682-7eb5231bbc76
        name: acr
        description: OpenID Connect scope for add acr (authentication context class reference) to the token
        protocol: openid-connect
        attributes:
          include.in.token.scope: "false"
          display.on.consent.screen: "false"
        protocolMappers:
          - id: bc946f16-8378-4edc-9137-f5d5db96da88
            name: acr loa level
            protocol: openid-connect
            protocolMapper: oidc-acr-mapper
            consentRequired: false
            config:
              id.token.claim: "true"
              access.token.claim: "true"
      - id: 47f93745-58c6-4f19-9ef4-768cd6df7ab7
        name: microprofile-jwt
        description: Microprofile - JWT built-in scope
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "false"
        protocolMappers:
          - id: ca164b36-12dc-47fc-b0e6-e40949a5042e
            name: upn
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: username
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: upn
              jsonType.label: String
          - id: 4314b495-934a-4948-b9ae-fc9c17354cf0
            name: groups
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            consentRequired: false
            config:
              multivalued: "true"
              user.attribute: foo
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: groups
              jsonType.label: String
      - id: 710757d5-c717-44de-ad25-2133cf75b0a6
        name: nameandterms
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
      - id: b4120472-4f73-4659-ae6b-d24bd45c4fa3
        name: address
        description: 'OpenID Connect built-in scope: address'
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
          consent.screen.text: ${addressScopeConsentText}
        protocolMappers:
          - id: 8bf14f81-76b3-4970-9993-a270b52ae28a
            name: address
            protocol: openid-connect
            protocolMapper: oidc-address-mapper
            consentRequired: false
            config:
              user.attribute.formatted: formatted
              user.attribute.country: country
              user.attribute.postal_code: postal_code
              userinfo.token.claim: "true"
              user.attribute.street: street
              id.token.claim: "true"
              user.attribute.region: region
              access.token.claim: "true"
              user.attribute.locality: locality
  instanceSelector:
    matchLabels:
      app: keycloak
