replicaCount: 1
image:
  repository: quay.io/eformat/superset
  pullPolicy: Always
  tag: "1.4.1"
imageDb:
  repository: registry.redhat.io/rhel8/postgresql-13
  pullPolicy: Always
  tag: "1-56"
imagePullSecrets: []
nameOverride: ""
nameOverrideDb: ""
fullnameOverride: ""
fullnameOverrideDb: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
serviceAccountDb:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi
resourcesInit:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
resourcesDb:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 300Mi
database:
  accessModes:
    - ReadWriteOnce
  storage: 2Gi
auth:
  default_role: ""
  client_id: ""
  client_secret: ""
  base_url: ""
  oidc_auth_url: ""
  redirect_uris: ""
  token_uri: ""
  logout_redirect_url: ""
avp:
  secretPath: ""
