{{- if .Values.users }}
{{ $realm := .Values.realm }}
{{ $doIt := false }}
{{- range $user := .Values.users }}
{{- if eq .clusterRole "edit" }}
{{ $doIt = true }}
{{- end }}
{{- end }}
{{- if $doIt }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-iam-{{ $realm }}
  namespace: {{ .Release.Namespace }}
subjects:
{{- range $user := .Values.users }}
{{- if eq .clusterRole "edit" }}
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ .username }}
{{- end }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}
{{- end }}
