---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-operator.fullname" . }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "spark-operator.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spark-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: QUARKUS_KUBERNETES_CLIENT_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: WATCH_NAMESPACES
          value: {{ .Release.Namespace }}
        - name: DEFAULT_SPARK_CLUSTER_IMAGE
          value: {{ .Values.sparkRuntimeImage }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8877
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8877
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: spark-operator
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ include "spark-operator-sa.fullname" . }}
      serviceAccountName: {{ include "spark-operator-sa.fullname" . }}
      terminationGracePeriodSeconds: 5
