{{- if .Values.clusterresourceoverride }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterresources-crd-reader
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - 'customresourcedefinitions'
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterresources-crd-reader-binding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterresources-crd-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-resources-wait-crd
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: crd-check
      image: quay.io/openshift/origin-cli:latest
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'while [ true ]; do oc get crd clusterresourceoverrides.operator.autoscaling.openshift.io; if [ $? -eq 0 ]; then break; fi ; sleep 5s; done']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  serviceAccount: default
  serviceAccountName: default
{{- end }}
